### ISSUE TITLE
- Webcatalog - MAILRULESTAG: MAC APP SUPPORT - SUGGESTION - FEEDBACK

### ISSUE THREAD

**Issue by questionanswertgs** [webcatalog/webcatalog-app#1043]
- disable all audio from all tabs (especially Tiktok related)

**Comment by questionanswertgs** [comment]
optionally add a way to add a list of favorite websites inside each tabs. this mean instead of having 90 tabs for 10 topics related to 9 social I would use just 10 tabs and the 9 social related account are directly available in each tab. so I would just see a list of 9 links and I choose which I want to visit now.

**Comment by questionanswertgs** [comment]
add option close app after x minutes of inactivity directly in the setting without need to configure for every Mac user such setting with 3apps.

**Comment by questionanswertgs** [comment]
-download folder different for each tab inside same .app
-improve library size cache and similar data, to reduce total size

**Comment by questionanswertgs** [comment]
- would be cool if we can install 1-2 chrome extension inside electron mac apps, like downloader extension

**Comment by questionanswertgs** [comment]
impossible to understand which tab has audio active

no way to disable audio at all once is active

**Comment by questionanswertgs** [comment]
optionally insert same link to multiple tab at once, for example by inserting link and choosing which tabs (such setting should be remain if we redo it, so after that we just need to insert a new link)

- add my google account picture to the sidebar, instead of google picture

- remove cmd + number from the sidebar at all (so we can have more tabs without scrolling).

**Comment by questionanswertgs** [comment]
- choose the size of the app without need to use bbt or other apps. i like how you remember the last used size, but wish i could switch between different size faster. so something where we can tell webcatalog resize the app with yy x zz starting at pixel ww - pp. then we simply choose this configuration or the other configuration.

another option is to use another 3app to do this resize, you should only save the different size.

**Comment by questionanswertgs** [comment]
if i drag drop a link from one browser to webcatalog i should have to options:

open link in current workspace (so i turn off message about where to open)

or show me a message "choose which tab"

**Comment by quanglam2807** [comment]
Thank you so much for the feedback! I'll try to work on these feedbacks soon.

**Comment by questionanswertgs** [comment]
- in the search app panel add a button "show finder folder"
- for me not important, but maybe some user wish to have a menubar launcher app (in the style of setapp)
- thinking to save the setting for some apps under /shared instead of /library = to avoid duplicate setting on different users.

**Comment by questionanswertgs** [comment]
maybe you think i'm crazy, but would be cool if you app is able to tab other apps.

so in such way we would have the lateral sidebar for tabs and a tab for apps over the navigation bar.

in such way we could merge for example 9 webcatalog apps in 1 (each with 9 tabs) and we could use 9*9= 81 tabs without need to switch app.

**Comment by questionanswertgs** [comment]
another point about png. at the moment i always need to open google png webcatalog app, search the png, download to png folder select photo and import it to tabs /apps. 

maybe the option "search png in google and add automatically plus save a copy in the folder png" would be better, without need to use a second app.

**Comment by questionanswertgs** [comment]
if not, maybe a way to save all png to a shared folder, so that we can add such png quickly directly in the tab setting by searching previous used png or by name. maybe a way to add png to some groups too.

**Comment by questionanswertgs** [comment]
Failed to uninstall Raindrop.... add for each app a setting show in finder. so we can manually delete it

**Comment by questionanswertgs** [comment]
add maybe a small icon to show that a specific tab has no login (don't know if this is possible), in that way we know we need to finish configuration before copying it to another mac user. on some tabs i see the number of notifications, but such numbers are not always available.

**Comment by questionanswertgs** [comment]
i still wish in future you can move all single folder saved inside /applicationsupport to /applicationsupport/webcatalog and then you add all new single folder here. in such way is much easier to understand if the folder is webcatalog related or not and to copy folder between users. i just need to visit webcatalog, without scrolling 1000+ folders (not related to webcatalog). is much easier to clean it too, since as i reported you, a lot of folders contain 700mb+ pro each app.

obviously if we install it inside user, and not if we install it under shared (like the other suggestion)

**Comment by questionanswertgs** [comment]
Abilita la riproduzione sicura nel tuo browser
Visita il sito dell'assistenza di Spotify per scoprire come.

doesn't work

**Comment by questionanswertgs** [comment]
add a panel "not installed app", so we don't need to scroll already installed apps.

**Comment by questionanswertgs** [comment]
or change background color of installed apps

**Comment by questionanswertgs** [comment]
or maybe simply add last added apps.

**Comment by questionanswertgs** [comment]
if i click go home on https://techcommunity.microsoft.com/t5/notes/composepage/note-to-user-id/xxxxxxxxx# to visit https://techcommunity.microsoft.com/t5/notes/privatenotespage/tab/outbox, this doesn't work at all

**Comment by questionanswertgs** [comment]
add a button to replace home url with the current opened url
